[metadata]
name = meshio-resqml
version = file: meshio_resqml/VERSION
author = Keurfon Luu
email = kluu@intera.com
description = An extension to support the RESQML format in meshio
url = https://github.com/keurfonluu/meshio-resqml
project_urls =
    Code=https://github.com/keurfonluu/meshio-resqml
    Issues=https://github.com/keurfonluu/meshio-resqml/issues
long_description_content_type = text/x-rst
platforms = any
classifiers =
    Operating System :: OS Independent
    Development Status :: 4 - Beta
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11

[options]
packages = find:
install_requires =
    importlib_metadata
    meshio >= 5.2, < 6.0
    resqpy >= 4.0

python_requires = >= 3.8
setup_requires =
    setuptools >= 42
    wheel 

[options.package_data]
meshio_resqml =
    VERSION
